### ISSUE TITLE
Let's finish the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/e-s2-evaluacion-intermedia-japocoinyenhoang#1]
Ahoy @japocoinyenhoang !!!

Here you have some tips to improve the exercise:

- [x] Link the external JS file correctly (watch the path!

Here you are a steps guide to complete it ;)

1. Save a reference to DOM elements in variables
2. Generate the random number and save it to a variable
3. Init counter of trials to 0
4. Define a function that executes when the user clicks on the button, that
  - increments the counter and paints its value in the HTML
  - collect the value of the HTML input and compare it with the random number
    - if they are equal, draw a 'You Win' message
    - if it's lower, draw a 'Too short' message
    - if it's higher, draw a 'Too long' message
5. Assign a listener to the button click to execute the previous function

Let me know if you have any doubts ;)

Go for it!!

**Comment by japocoinyenhoang** [comment]
Hi @oneeyedman, 
First of all, thanks for your tips and the guide,  they were very very useful.
I did the exercises, and it seems that it works, but I don't know exactly how. Anyway, I will check it again, and try to understand it better.
Thanks for your help.
Have a nice day.

**Comment by oneeyedman** [comment]
Great job @japocoinyenhoang!

![Well done](https://media.giphy.com/media/26uffIRfNMzrTCvok/giphy-downsized.gif)
